### ISSUE TITLE
Open other endpoints

### ISSUE THREAD

**Issue by BritishBenji** [Artemis21/discord-role-api#2]
Looking to open up other endpoints (mainly to get a list of banned users)
Would this be a trivial task?

I'd be looking to make it myself if it's not too difficult and make a pull request if it's wanted

**Comment by Artemis21** [comment]
Hi! This should certainly be possible. A pull request would be welcome as long as it's consistently styled and well documented.

However, you should note that this project is not maintained currently. For example, it still uses Discord.py, a library which is no longer maintained (it should be relatively trivial to switch to an alternative library like Nextcord).
